# Generated by Django 5.0.3 on 2024-03-19 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('profile_image', models.ImageField(null=True, upload_to='')),
                ('login', models.CharField(choices=[('ADMIN', 'Admin'), ('PATIENT', 'Patient'), ('NURSE', 'Nurse')], max_length=7)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('degree', models.CharField(choices=[('A', 'Associate Degree in Nursing'), ('D', 'Diploma in Nursing'), ('L', 'Licensed Practical Nurse'), ('AD', 'Advanced practice registered nurses')], max_length=7)),
                ('specialty', models.CharField(blank=True, choices=[('1', 'قسم تمريض الباطني والجراحي'), ('2', 'قسم تمريض العناية الحرجة والطوارئ'), ('3', 'قسم تمريض النسا والتوليد'), ('4', 'قسم تمريض الأطفال'), ('5', 'قسم التمريض النفسي والصحة العقلية'), ('6', 'قسم إدارة التمريض'), ('7', 'قسم تمريض المسنين'), ('8', 'قسم تمريض صحة المجتمع')], max_length=50, null=True)),
                ('university_grade', models.CharField(choices=[('1', 'Pass'), ('2', 'Good'), ('3', 'Verygood'), ('4', 'Excellent'), ('5', 'Superior')], max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.TextField(max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.TextField(max_length=100, null=True)),
                ('national_image', models.ImageField(upload_to='')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('satuts', models.BooleanField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, choices=[('1', 'قسم تمريض الباطني والجراحي'), ('2', 'قسم تمريض العناية الحرجة والطوارئ'), ('3', 'قسم تمريض النسا والتوليد'), ('4', 'قسم تمريض الأطفال'), ('5', 'قسم التمريض النفسي والصحة العقلية'), ('6', 'قسم إدارة التمريض'), ('7', 'قسم تمريض المسنين'), ('8', 'قسم تمريض صحة المجتمع')], max_length=50, null=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_task', models.CharField(blank=True, max_length=200, null=True)),
                ('now_task', models.CharField(blank=True, max_length=200, null=True)),
                ('next_task', models.CharField(blank=True, max_length=200, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('comments', models.TextField()),
                ('rate', models.FloatField(blank=True, max_length=10, null=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
